# This file was generated by GoReleaser. DO NOT EDIT.
cask "t5s" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "88076c799bc52fdc10e352a5ab61002e43def9c0f2ae39e88ec079fd81f45998"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f8b726d60ef2156d28efd6f2e58d3554e2eb968a584a0d2be13531025e873f1"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a3ea32aef28eaa92c218d5003f63e5525eb9fe88f12b4930cb6d8f17b07ec308"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2dce59d28fd50213fa99f1935bbd732134fac4373de08dc7b112042b0ffcbe99"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_linux_amd64.tar.gz"
    end
  end

  name "t5s"
  desc "Share localhost with only the people you allow"
  homepage "https://github.com/sakusi4/t5s"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "cloudflared",
    ]

  binary "t5s"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/t5s"]
    end
  end

  # No zap stanza required
end
