# This file was generated by GoReleaser. DO NOT EDIT.
cask "t5s" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "2d4f7eabc46aa0ae21e821cd34b0789a8c400391fa5a2140aea0f8333fd50d29"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0069be4a6ca114c8c0c478f010c0abe343702232372cc3e62cb09c1c3e8fe042"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6bf7353fa55d9906994960fff9b7f9307c57042e42a1ec2f84bcb89dd698a736"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e766153f777508cc3442922470ec8f4b0e2a78a55ebabb69b07829ab4f59a56"
      url "https://github.com/sakusi4/t5s/releases/download/v#{version}/t5s_#{version}_linux_amd64.tar.gz"
    end
  end

  name "t5s"
  desc "Share localhost with only the people you allow"
  homepage "https://github.com/sakusi4/t5s"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "cloudflared",
    ]

  binary "t5s"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/t5s"]
    end
  end

  # No zap stanza required
end
